/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author J Girish
 */
public class S_dash extends javax.swing.JFrame {

    /**
     * Creates new form S_dash
     */
    String name;
    String n1,t1_name,t2_name,t3_name,t4_name,t5_name,day;
    public S_dash() {
        initComponents();
    }
public S_dash(String name) {
        initComponents();
        this.name=name;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 429, 96);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1630, 10, 210, 43);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("New Appointment request :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(560, 230, 190, 10);

        jToggleButton1.setText("ok");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(890, 220, 87, 25);

        jToggleButton2.setText("Manage Previous Appointments??");
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(1650, 1030, 223, 25);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("School  of       :-   ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 220, 110, 26);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Engineering", "Management", "Humanities" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(890, 210, 110, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText(" Department   :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 310, 100, 20);

        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(890, 310, 90, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText(" Name       :-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 430, 80, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(890, 430, 100, 30);

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1090, 433, 80, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("  Date        :-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(590, 550, 110, 30);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1100, 550, 73, 25);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(1140, 690, 300, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(640, 690, 300, 30);

        jButton3.setText("10:00-11:00");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 820, 120, 25);

        jButton4.setText("11:00-12:00");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(800, 820, 110, 25);

        jButton5.setText("12:00-13:00");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(970, 820, 100, 25);

        jButton6.setText("13:00-14:00");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1120, 820, 100, 25);

        jButton7.setText("14:00-15:00");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1270, 820, 100, 25);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(900, 560, 100, 22);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        jLabel3.setVisible(false);
        jToggleButton1.setVisible(false);
        jLabel4.setVisible(true);
        jComboBox1.setVisible(true);
          jLabel5.setVisible(true);
         jComboBox2.setVisible(true);
         jLabel6.setVisible(true);
         jTextField3.setVisible(true);
         jTextField1.setVisible(true);
         jTextField2.setVisible(true);
         jLabel7.setVisible(true);
          jButton1.setVisible(true);
          jButton2.setVisible(true);
          jButton3.setVisible(true);
          jButton4.setVisible(true);
          jButton5.setVisible(true);
          jButton6.setVisible(true);
          jButton7.setVisible(true);
          
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jLabel2.setText("Welcome"+" "+name);
        jLabel4.setVisible(false);
        jComboBox1.setVisible(false);
         jLabel5.setVisible(false);
         jComboBox2.setVisible(false);
         jLabel6.setVisible(false);
         jTextField3.setVisible(false);
         jTextField2.setVisible(false);
         jTextField1.setVisible(false);
         jDateChooser1.setVisible(false);
         jLabel7.setVisible(false);
          jButton1.setVisible(false);
          jButton2.setVisible(false);
          jButton3.setVisible(false);
          jButton4.setVisible(false);
          jButton5.setVisible(false);
          jButton6.setVisible(false);
          jButton7.setVisible(false);
          
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jComboBox2.removeAllItems();
        String g=jComboBox1.getSelectedItem().toString();
          try
    {
      // create a mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbms";
      Class.forName("com.mysql.jdbc.Driver");
        // create a sql date object so we can use it in our INSERT statement
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "kalikrishna")) {
            // create a sql date object so we can use it in our INSERT statement
  
            // the mysql insert statement
            String query = " select department from Professor where school=? group by department";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, g);
            // execute the preparedstatement
            ResultSet rs = preparedStmt.executeQuery();
             jComboBox2.addItem("Select");
            while(rs.next())
            {
               jComboBox2.addItem(rs.getNString(1));
 
            }
           
        }
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
      e.printStackTrace();
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           String g=jComboBox2.getSelectedItem().toString();
           String h=jTextField1.getText();
        try
    {
      // create a mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbms";
      Class.forName("com.mysql.jdbc.Driver");
        // create a sql date object so we can use it in our INSERT statement
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "kalikrishna")) {
            // create a sql date object so we can use it in our INSERT statement
  
            // the mysql insert statement
            String query = " select name from Professor where department=? and name=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, g);
            preparedStmt.setString(2, h);
            // execute the preparedstatement
            ResultSet rs = preparedStmt.executeQuery();
            // jComboBox2.addItem("Select");
            if(rs.next())
            {
               jTextField3.setText("-->Please Choose the Date for Appointment");
               jDateChooser1.setVisible(true);
              //jTextArea1.setVisible(false);
 
            }
            else
                jTextField3.setText("On Match found");
        }
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
      e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      
        String h=jTextField1.getText();
        if(jDateChooser1.getDate().toString().startsWith("Mon"))
            day="Mon";
        else if(jDateChooser1.getDate().toString().startsWith("Tue"))
            day="Tue";
        else if(jDateChooser1.getDate().toString().startsWith("wed"))
            day="Wed";
        else if(jDateChooser1.getDate().toString().startsWith("Thu"))
            day="Thu";
        else if(jDateChooser1.getDate().toString().startsWith("Fri"))
            day="Fri";
        else
        { jTextField3.setText("University holiday");
            day="null";
        }     
       System.out.println(day+" "+h);
        try
    {
      // create a mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbms";
      Class.forName("com.mysql.jdbc.Driver");
        // create a sql date object so we can use it in our INSERT statement
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "kalikrishna")) {
            // create a sql date object so we can use it in our INSERT statement
  
            // the mysql insert statement
            String query = " select * from tue where name=? ";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
          //  preparedStmt.setString(1, day);
            preparedStmt.setString(1, h);
            System.out.println("ji");
            // execute the preparedstatement
            ResultSet rs = preparedStmt.executeQuery();
                        System.out.println("ji");

            if(rs.next())
            {
              n1=rs.getNString(1);
              t1_name=rs.getNString(2);
              t2_name=rs.getNString(3);
              t3_name=rs.getNString(4);
              t4_name=rs.getNString(5);
              t5_name=rs.getNString(6);
 
            }
           System.out.println(n1+" "+t1_name+" "+t2_name+" "+t3_name+" "+t4_name+" "+t5_name);
        }
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
      e.printStackTrace();
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         if(t1_name==null)
        {
                   try
    {
      // create a mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbms";
      Class.forName("com.mysql.jdbc.Driver");
        // create a sql date object so we can use it in our INSERT statement
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "kalikrishna")) {
            // create a sql date object so we can use it in our INSERT statement
  
            // the mysql insert statement
            String query = " update table ? set t1_name=? where name=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, day);
            preparedStmt.setString(2, name);
             preparedStmt.setString(3,n1);
            // execute the preparedstatement
            preparedStmt.execute();
            
        }
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
      e.printStackTrace();
    }
            
        }
        else if(t1_name.equalsIgnoreCase("Occupied")||t1_name.equalsIgnoreCase("class")||t1_name.equalsIgnoreCase("Lunch"))
        {
            jTextField2.setText("Please select different slot");
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(t2_name==null)
        {
                   try
    {
      // create a mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbms";
      Class.forName("com.mysql.jdbc.Driver");
        // create a sql date object so we can use it in our INSERT statement
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "kalikrishna")) {
            // create a sql date object so we can use it in our INSERT statement
  
            // the mysql insert statement
            String query = " update table ? set t1_name=? where name=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, day);
            preparedStmt.setString(2, name);
             preparedStmt.setString(3,n1);
            // execute the preparedstatement
            preparedStmt.execute();
            
        }
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
      e.printStackTrace();
    }
            
        }
        else if(t2_name.equalsIgnoreCase("Occupied")||t2_name.equalsIgnoreCase("class")||t2_name.equalsIgnoreCase("Lunch"))
        {
            jTextField2.setText("Please select different slot");
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(t3_name==null)
        {
                   try
    {
      // create a mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbms";
      Class.forName("com.mysql.jdbc.Driver");
        // create a sql date object so we can use it in our INSERT statement
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "kalikrishna")) {
            // create a sql date object so we can use it in our INSERT statement
  
            // the mysql insert statement
            String query = " update table ? set t1_name=? where name=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, day);
            preparedStmt.setString(2, name);
             preparedStmt.setString(3,n1);
            // execute the preparedstatement
            preparedStmt.execute();
            
        }
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
      e.printStackTrace();
    }
            
        }
        else if(t3_name.equalsIgnoreCase("Occupied")||t3_name.equalsIgnoreCase("class")||t3_name.equalsIgnoreCase("Lunch"))
        {
            jTextField2.setText("Please select different slot");
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(t4_name==null)
        {
                   try
    {
      // create a mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbms";
      Class.forName("com.mysql.jdbc.Driver");
        // create a sql date object so we can use it in our INSERT statement
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "kalikrishna")) {
            // create a sql date object so we can use it in our INSERT statement
  
            // the mysql insert statement
            String query = " update table ? set t1_name=? where name=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, day);
            preparedStmt.setString(2, name);
             preparedStmt.setString(3,n1);
            // execute the preparedstatement
            preparedStmt.execute();
            
        }
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
      e.printStackTrace();
    }
            
        }
        else if(t4_name.equalsIgnoreCase("Occupied")||t4_name.equalsIgnoreCase("class")||t4_name.equalsIgnoreCase("Lunch"))
        {
            jTextField2.setText("Please select different slot");
        } 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(t5_name==null)
        {
                   try
    {
      // create a mysql database connection
      String myDriver = "com.mysql.jdbc.Driver";
      String myUrl = "jdbc:mysql://localhost:3306/dbms";
      Class.forName("com.mysql.jdbc.Driver");
        // create a sql date object so we can use it in our INSERT statement
        try (Connection conn = DriverManager.getConnection(myUrl, "root", "kalikrishna")) {
            // create a sql date object so we can use it in our INSERT statement
  
            // the mysql insert statement
            String query = " update table ? set t5_name=? where name=?";
            
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            preparedStmt.setString(1, day);
            preparedStmt.setString(2, name);
             preparedStmt.setString(3,n1);
            // execute the preparedstatement
            preparedStmt.execute();
            
        }
    }
    catch (Exception e)
    {
      System.err.println("Got an exception!");
      System.err.println(e.getMessage());
      e.printStackTrace();
    }
            
        }
        else if(t5_name.equalsIgnoreCase("Occupied")||t5_name.equalsIgnoreCase("class")||t5_name.equalsIgnoreCase("Lunch"))
        {
            jTextField2.setText("Please select different slot");
        } 
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_dash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
